routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/', ['as'=>'home', 'uses'=>'GeneralController@index']);

Route::get('/login', ['as' => 'login',
    function () {
        return redirect()->route('home');
    }
]);

Route::post('/login',    ['as'=>'login', 'uses'=>'GeneralController@postLogin']);
Route::post('/register', ['as'=>'register', 'uses'=>'GeneralController@postRegister']);

Route::get('/register', ['as' => 'register',
    function () {
        return redirect()->route('home');
    }
]);


Route::group(['middleware' => ['auth', 'myApplication']], function() {
    Route::post('applications/postupdate/{id}', ['as'=>'applications.postupdate', 'uses'=>'ApplicationController@postupdate']);
    Route::post('applications/approve/{id}',    ['as'=>'applications.approve', 'uses'=>'ApplicationController@approve']);
    Route::resource('applications', 'ApplicationController');
});

Route::group(['prefix' => 'dashboard', 'namespace' => 'Dashboard', 'middleware' => ['auth', 'isAdmin']], function() {
    Route::get('/', ['as' => 'dashboard', 'uses' => 'AdminController@index']);
    Route::resource('users', 'UserController');
    Route::resource('roles', 'RoleController', ['except' => 'show']);
    Route::resource('permissions', 'PermissionController', ['except' => 'show']);
    Route::get('applications-admin/show2/{id}',    ['as'=>'applications-admin.show2',   'uses'=>'ApplicationController@show2']);
    Route::post('applications-admin/approve/{id}', ['as'=>'applications-admin.approve','uses'=>'ApplicationController@approve']);
    Route::resource('applications-admin', 'ApplicationController');
    Route::resource('pages', 'PageController');
    Route::match(['get', 'post'],'/options',    ['as'=>'options', 'uses'=>'AdminController@options']);
});

Route::get('page/{id}',     ['as'=>'page',  'uses'=>'GeneralController@page']);

app/Permission.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Permission extends Model
{
    protected $table = 'permissions';
    public $primaryKey  = 'id';
}

app/Http/Controllers/Dashboard/AdminController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Traits\BreadcrumbTrait;

use App\User;
use App\Application;
use App\Option;
use App\Page;
use Auth;
use App\Http\Controllers\Controller;

use Session;

class AdminController extends Controller 
{ 

    use BreadcrumbTrait;

    public function index()
    {
        $stat = [
            'users' => User::count(),
            'wait' => Application::where('status_id','=','2')->count(),
            'complete' => Application::where('status_id','=','5')->count(),
        ];
        return view('dashboard.index', [
            'data' => self::getBreadcrumb(),
            'stat' => $stat,
        ]);
    }

    public function options(Request $request)
    {

        if ($request->isMethod('post')) {
            foreach ($request->all() as $key => $value) {
                Option::setOption($key, $value ? $value : '');
            }
            return redirect()->route('options')
                ->with('flash_message', __('Options updated successfully'));
        }        
        return view('dashboard.options',[
                'data' => self::getBreadcrumb(),
                'options' => Option::pluck('value','key'),
                'infopagesAnnex1' => Page::getList( Option::getOption('infopagesAnnex1') ),
                'infopagesAnnex2' => Page::getList( Option::getOption('infopagesAnnex2') ),
                'pages' => Page::all(),
            ]);
    }

}

app/Http/Controllers/Dashboard/ApplicationController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Traits\BreadcrumbTrait;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

use App\Http\Controllers\Controller;
use App\Application;

use App\Mail\OrderShipped;
use Illuminate\Support\Facades\Mail;

class ApplicationController extends Controller
{

    use BreadcrumbTrait;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request) {        
        return view('dashboard.applications.index', [
            'data' => self::getBreadcrumb(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $model = Application::findOrFail($id);
        return response([
            'f1' => $model->showApplicationForm('f1'),
            'f2' => $model->showApplicationForm('f2'),
            'f3' => $model->showApplicationForm('f3'),
            'f4' => $model->showApplicationForm('f4'),
            'file' => isset($model->data->file) ? $model->data->file : (object)[],
            'agenda' => is_array($model->agenda) ? $model->agenda : (object)[],
        ], 200);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    # функция для получения аяксом данных для datatable
    public function datatable(Request $request)
    {
        $where = [];
        if ($request->table == 'approve'){
            $where = [['status_id','=',2]];
        } else if( $request->table == 'complete' ) {
            $where = [['status_id','=',5]];
        } else {
            $where = [['status_id','<>',2],['status_id','<>',5]];
        }
        $columns = [
            0 => 'id',
            1 => 'name',
            2 => 'status_id',
            3 => 'created_at',
        ];

        $totalData = Application::where($where)->count();
        $limit = $request->input('length');
        $start = $request->input('start');
        $order = $columns[$request->input('order.0.column')];
        $dir = $request->input('order.0.dir');

        if(empty($request->input('search.value'))){
            $temp = Application::where($where)->offset($start)
                ->orderby($order,$dir)
                ->limit($limit);
                $models = $temp->get();
            $totalFiltered = $totalData;
        } else {
            $search = $request->input('search.value');
            $temp = Application::where($where)
                ->offset($start)
                ->orderby($order,$dir)
                ->limit($limit);
                $models = $temp->get();
            $temp = Application::where($where);
                $totalFiltered = $temp->count();
        }
        
        $data = [];
        if($models){
            foreach($models as $model){
                $nestedData['id'] = $model->id;
                $nestedData['name'] = $model->user->name;
                $nestedData['status'] = trans('custom.status.'.$model->status_id);
                $nestedData['created'] = $model->created_at->format('d.m.Y');
                $nestedData['actions'] = '<div class="list-icons">';
                    $nestedData['actions'] .= '<a href="'.route('applications-admin.show', $model->id).'" class="list-icons-item btn-view" title="'.__('annex 1').'" data-toggle="modal" data-target="#modal-view"><i class="icon-eye"></i></a>';
                    if($model->status_id==2){
                        $nestedData['actions'] .= '<a href="'.route('applications-admin.approve', $model->id).'" class="list-icons-item text-success-600 btn-approve" title="'.__('Approve').'" data-toggle="modal" data-target="#modal-approve"><i class="icon-check"></i></a>';
                    }
                    if($model->status_id>2){
                        $nestedData['actions'] .= '<a href="'.route('applications-admin.show', $model->id).'" class="list-icons-item btn-view2" title="'.__('annex 2').'" data-toggle="modal" data-target="#modal-view2"><i class="icon-clipboard3"></i></a>';
                    }
                $nestedData['actions'] .= '</div>';
                $data[] = $nestedData;
            }
        }
        $json_data = [
            "draw" => (int)$request->input('draw'),
            "recordsTotal" => (int)$totalData,
            "recordsFiltered" => (int)$totalFiltered,
            "data" => $data,

        ];
        echo json_encode($json_data);
    }

    public function approve(Request $request, $id)
    {
        $model = Application::findOrFail($id);
        $model->update( [ 'status_id'=> 3 ] );

        $data = [
                'subject' => 'Application has been approved',
                'title' => 'Application has been approved',
                'content' => 'My content',
                'user' => $model->user->name,
            ];

        Mail::to( $model->user->email )->send(new OrderShipped($data));
        //Mail::to($request->email)
            //->cc('waddon@narod.ru')
            //->queue(new OrderShipped($data));

        return response([
            'message' => trans('cms.alert-update', ['name' => $model->created_at]),
        ], 200);
    }


    // public function show2($id)
    // {
    //     $model = Application::findOrFail($id);
    //         $result = is_object($model->annex2) ? $model->annex2 : (object)[];
    //         $result->p1_q10_1 = isset($result->p1_q10_1_1)&&$result->p1_q10_1_1 ? 'Yes' : 'No';
    //         $result->p1_q10_2 = isset($result->p1_q10_2_1)&&$result->p1_q10_2_1 ? 'Yes' : 'No';
    //         $result->p1_q10_3 = isset($result->p1_q10_3_1)&&$result->p1_q10_3_1 ? 'Yes' : 'No';
    //         $result->p1_q10_4 = isset($result->p1_q10_4_1)&&$result->p1_q10_4_1 ? 'Yes' : 'No';
    //         $result->p1_q10_5 = isset($result->p1_q10_5_1)&&$result->p1_q10_5_1 ? 'Yes' : 'No';
    //         $result->p1_q10_6 = isset($result->p1_q10_6_1)&&$result->p1_q10_6_1 ? 'Yes' : 'No';
    //         $result->p1_q10_7 = isset($result->p1_q10_7_1)&&$result->p1_q10_7_1 ? 'Yes' : 'No';
    //         $result->p1_q10_8 = isset($result->p1_q10_8_1)&&$result->p1_q10_8_1 ? 'Yes' : 'No';
    //         $result->p1_q10_9 = isset($result->p1_q10_9_1)&&$result->p1_q10_9_1 ? 'Yes' : 'No';
    //         $result->p1_q10_10 = isset($result->p1_q10_10_1)&&$result->p1_q10_10_1 ? 'Yes' : 'No';
    //         $result->p1_q10_11 = isset($result->p1_q10_11_1)&&$result->p1_q10_11_1 ? 'Yes' : 'No';
    //         $result->p1_q10_12 = isset($result->p1_q10_12_1)&&$result->p1_q10_12_1 ? 'Yes' : 'No';
    //         $agenda = is_array($model->agenda) ? $model->agenda : (object)[];
    //     return response([
    //         'message' => $result,'agenda' => $agenda,
    //     ], 200);
    // }
}

app/Http/Controllers/Dashboard/PageController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Traits\BreadcrumbTrait;

use Illuminate\Http\Request;
use App\Http\Requests\StorePageRequest;
use Illuminate\Support\Facades\Auth;

use App\Http\Controllers\Controller;
use App\Page;
use App\Option;

class PageController extends Controller
{

    use BreadcrumbTrait;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request) {        
        return view('dashboard.pages.index', [
            'data' => self::getBreadcrumb(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $model = new Page;
        return view('dashboard.pages.form', [
                'model'=>$model,
                'data' => self::getBreadcrumb(),
            ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePageRequest $request)
    {
        $array = [
                'name'   =>$request->name,
                'slug'   =>$request->slug,
                'content'=>$request->content ? $request->content : '',
                'public' =>$request->public ? true : false,
            ];
        $model = Page::create($array);
        return response([
            'message' => __('Element created successfully'),
            'formAction' => route('pages.update', $model->id),
        ], 200);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $model = Page::findOrFail($id);
        return view('dashboard.pages.show', [
                'model'=>$model,
                'data' => self::getBreadcrumb(),
            ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = Page::findOrFail($id);
        return view('dashboard.pages.form', [
                'model'=>$model,
                'data' => self::getBreadcrumb(),
            ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StorePageRequest $request, $id)
    {
        $model = Page::findOrFail($id);
        $array = [
                'name'   =>$request->name,
                'slug'   =>$request->slug,
                'content'=>$request->content ? $request->content : '',
                'public' =>$request->public ? true : false,
            ];
        $model->update($array);
        return response([
            'message' => __('Element updated successfully'),
            'formAction' => route('pages.update', $model->id),
        ], 200);
    }

    /**
     * Move to trash the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function delete(Request $request, $id)
    {
        $model = Page::withTrashed()->findOrFail($id);
        $model->delete();
        return response([], 200);
    }

    /**
     * Restore from trash the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function restore(Request $request, $id)
    {
        $model = Page::onlyTrashed()->findOrFail($id);
        $model->restore();
        return response([], 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $model = Page::withTrashed()->findOrFail($id);
        $model->forceDelete();
        return response([], 200);
    }


    /**
     * Get list of data for datatable.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function datatable(Request $request)
    {
        return json_encode( Page::getListForDatatable($request) );
    }


}

resources/views/dashboard/permissions/create.blade.php
@extends('layouts.layout-admin')

@section('content')

{{ Form::open(array('route' => 'permissions.index')) }}

    <div class="d-flex align-items-start flex-column flex-md-row">

        <!-- Left content -->
        <div class="order-2 order-md-1 w-100">
            <div class="card" id="release">
                <div class="card-header header-elements-inline">
                    <h5 class="card-title">Parameters</h5>
                    <div class="header-elements">
                        <div class="list-icons">
                            <a class="list-icons-item" data-action="collapse"></a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        {{ Form::label('name', 'Name', ['class'=>'small text-muted font-italic']) }}
                        {{ Form::text('name', '', array('class' => 'form-control'. ($errors->has('name') ? ' is-invalid' : '' ))) }}
                        @if($errors->has('name'))
                            @foreach ($errors->get('name') as $message)
                                <div class="invalid-feedback">{{ $message }}</div>
                            @endforeach
                        @endif
                    </div>
                    <div class='form-group'>
                        <label class="small text-muted font-italic">Roles</label>
                        @if(!$roles->isEmpty())
                            @foreach ($roles as $role) 
                                <div class="custom-control custom-checkbox">
                                    {{ Form::checkbox('roles[]',  $role->id , null, ['id' => $role->name, 'class' => 'custom-control-input']) }}
                                    {{ Form::label($role->name, ucfirst($role->name), ['class' => 'custom-control-label']) }}
                                </div>
                            @endforeach
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <!-- /left content -->

        <!-- Right sidebar component -->
        <div class="sidebar-sticky w-100 w-md-auto order-1 order-md-2">
            <div class="sidebar sidebar-light sidebar-component sidebar-component-right sidebar-expand-md mb-3">
                <div class="sidebar-content">
                    <div class="card">
                        <div class="card-header bg-transparent header-elements-inline">
                            <span class="text-uppercase font-size-sm font-weight-semibold">Навигация</span>
                            <div class="header-elements">
                                <div class="list-icons">
                                    <a class="list-icons-item" data-action="collapse"></a>
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                                <div class="btn-group" style="width: 100%;">
                                    <button type="submit" id="submit" class="btn btn-success w-50" title="Save"><i class="icon-floppy-disk"></i></button>
                                    <a href="{{ route('permissions.index') }}" class="btn btn-danger w-50" title="Exit"><i class="icon-esc"></i></a>
                                </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /right sidebar component -->

    </div>

{{ Form::close() }}

@endsection

resources/views/dashboard/permissions/edit.blade.php
@extends('layouts.layout-admin')

@section('content')

{{ Form::model($permission, array('route' => array('permissions.update', $permission->id), 'method' => 'PUT')) }}

<div class="d-flex align-items-start flex-column flex-md-row">

    <!-- Left content -->
    <div class="order-2 order-md-1 w-100">
        <div class="card" id="release">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">Параметры</h5>
                <div class="header-elements">
                    <div class="list-icons">
                        <a class="list-icons-item" data-action="collapse"></a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                    <div class="form-group">
                        {{ Form::label('name', 'Name', ['class'=>'small text-muted font-italic']) }}
                        {{ Form::text('name', null, array('class' => 'form-control'. ($errors->has('name') ? ' is-invalid' : '' ))) }}
                        @if($errors->has('name'))
                            @foreach ($errors->get('name') as $message)
                                <div class="invalid-feedback">{{ $message }}</div>
                            @endforeach
                        @endif
                    </div>
            </div>
        </div>
    </div>
    <!-- /left content -->

    <!-- Right sidebar component -->
    <div class="sidebar-sticky w-100 w-md-auto order-1 order-md-2">
        <div class="sidebar sidebar-light sidebar-component sidebar-component-right sidebar-expand-md mb-3">
            <div class="sidebar-content">
                <div class="card">
                    <div class="card-header bg-transparent header-elements-inline">
                        <span class="text-uppercase font-size-sm font-weight-semibold">Navigation</span>
                        <div class="header-elements">
                            <div class="list-icons">
                                <a class="list-icons-item" data-action="collapse"></a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="btn-group" style="width: 100%;">
                            <button type="submit" id="submit" class="btn btn-success w-50" title="Save"><i class="icon-floppy-disk"></i></button>
                            <a href="{{ route('permissions.index') }}" class="btn btn-danger w-50" title="Exit"><i class="icon-esc"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /right sidebar component -->

</div>

{{ Form::close() }}

@endsection

resources/views/dashboard/permissions/index.blade.php
@extends('layouts.layout-admin')

@section('content')
    <div class="card mb-3">

        <div class="card-body">
            <ul class="nav nav-tabs nav-tabs-highlight">
                <li class="nav-item"><a href="#tab-active" class="nav-link active" data-toggle="tab"><i class="icon-menu7 mr-2"></i> Active</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane fade show active" id="tab-active">
                    <div class="table-responsive">
                        <table class="table datatable-basic table-striped dataTable no-footer mb-3 w-100" id="datatableActive">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Roles</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
                <div class="d-flex mt-3">
                    <a href="{{ route('permissions.create') }}" class="btn btn-success" title="create"><i class="icon-file-plus"></i></a>
                </div>
            </div>

        </div>
    </div>

@endsection

@section('scripts')
<script>
    var pageLength = 10;
    var columns = [
            {"data":"id"},
            {"data":"name"},
            {"data":"roles","searchable":false,"orderable":false},
            {"data":"actions","searchable":false,"orderable":false}
        ];
    var columnDefs = [
            { "targets": 0, "className": "text-center", },
            { "targets": 3, "className": "text-right", },
        ];


    var tableActive = $("#datatableActive").DataTable({
        "autoWidth" : true,
        "responsive": true,
        "processing": true,
        "serverSide": true,
        "pageLength": pageLength,
        "bSortCellsTop": true,
        "order": [[ 0, "desc" ]],
        "ajax": {
            "url": "{{route('permissions.datatable')}}",
            "dataType": "json",
            "type": "POST",
            "data": {"_token":"{{ csrf_token() }}", "table":"active"},
        },
        "columns":columns,
        'columnDefs': columnDefs,
    });

</script>
@endsection
@section('modals')
@include('template-parts.modal-ajax-destroy')
@endsection