routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/', ['as'=>'home', 'uses'=>'GeneralController@index']);

Route::get('/login', ['as' => 'login',
    function () {
        return redirect()->route('home');
    }
]);

Route::post('/login',    ['as'=>'login', 'uses'=>'GeneralController@postLogin']);
Route::post('/register', ['as'=>'register', 'uses'=>'GeneralController@postRegister']);

Route::get('/register', ['as' => 'register',
    function () {
        return redirect()->route('home');
    }
]);


Route::group(['middleware' => ['auth', 'myApplication']], function() {
    Route::post('applications/postupdate/{id}', ['as'=>'applications.postupdate', 'uses'=>'ApplicationController@postupdate']);
    Route::post('applications/approve/{id}',    ['as'=>'applications.approve', 'uses'=>'ApplicationController@approve']);
    Route::resource('applications', 'ApplicationController');
});

Route::group(['prefix' => 'dashboard', 'namespace' => 'Dashboard', 'middleware' => ['auth', 'isAdmin']], function() {
    Route::get('/', ['as' => 'dashboard', 'uses' => 'AdminController@index']);
    Route::resource('users', 'UserController');
    Route::resource('roles', 'RoleController', ['except' => 'show']);
    Route::resource('permissions', 'PermissionController', ['except' => 'show']);
    Route::get('applications-admin/show2/{id}',    ['as'=>'applications-admin.show2',   'uses'=>'ApplicationController@show2']);
    Route::post('applications-admin/approve/{id}', ['as'=>'applications-admin.approve','uses'=>'ApplicationController@approve']);
    Route::resource('applications-admin', 'ApplicationController');
    Route::resource('pages', 'PageController');
    Route::match(['get', 'post'],'/options',    ['as'=>'options', 'uses'=>'AdminController@options']);
});

Route::get('page/{id}',     ['as'=>'page',  'uses'=>'GeneralController@page']);

resources/views/menu/breadcrumb-line-header-elements.blade.php
                        <div class="breadcrumb justify-content-center">
                            <a href="#" class="breadcrumb-elements-item">
                                <i class="icon-comment-discussion mr-2"></i>
                                Support
                            </a>

                            <div class="breadcrumb-elements-item dropdown p-0">
                                <a href="#" class="breadcrumb-elements-item dropdown-toggle" data-toggle="dropdown">
                                    <i class="icon-gear mr-2"></i>
                                    Settings
                                </a>

                                <div class="dropdown-menu dropdown-menu-right">
                                    <a href="#" class="dropdown-item"><i class="icon-user-lock"></i> Account security</a>
                                    <a href="#" class="dropdown-item"><i class="icon-statistics"></i> Analytics</a>
                                    <a href="#" class="dropdown-item"><i class="icon-accessibility"></i> Accessibility</a>
                                    <div class="dropdown-divider"></div>
                                    <a href="#" class="dropdown-item"><i class="icon-gear"></i> All settings</a>
                                </div>
                            </div>
                        </div>

resources/views/menu/breadcrumb.blade.php
<div class="breadcrumb">
    @if(isset($data['breadcrumbs']))
        @foreach($data['breadcrumbs'] as $key => $breadcrumb)
            @if (count($data['breadcrumbs'])!=$key+1)
                <a href="{{$breadcrumb['url']}}" class="breadcrumb-item">{!!$breadcrumb['title']!!}</a>
            @else
                <span class="breadcrumb-item active">{!!$breadcrumb['title']!!}</span>
            @endif
        @endforeach
    @else
        <a href="{{route('home')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
        <span class="breadcrumb-item active">Dashboard</span>
    @endif
</div>

resources/views/menu/current-costs.blade.php
<div class="card">
    <div class="card-header header-elements-inline">
        <h6 class="card-title">Monthly spending</h6>
    </div>
    <div class="table-responsive">
        <table class="table text-nowrap">
            <thead>
                <tr>
                    <th class="w-100">Category</th>
                    <th>Plan</th>
                    <th>Fact</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <div class="d-flex align-items-center">
                            <div class="mr-3">
                                <a href="#" class="btn bg-primary-400 rounded-round btn-icon btn-sm legitRipple">
                                    <i class="icon-home7"></i>
                                </a>
                            </div>
                            <div><a href="#" class="text-default font-weight-semibold letter-icon-title">Home</a></div>
                        </div>
                    </td>
                    <td class="text-right"><h6 class="text-muted mb-0">2 000.00</h6></td>
                    <td class="text-right"><h6 class="font-weight-semibold mb-0">0.00</h6></td>
                </tr>

                <tr>
                    <td>
                        <div class="d-flex align-items-center">
                            <div class="mr-3">
                                <a href="#" class="btn bg-danger-400 rounded-round btn-icon btn-sm legitRipple">
                                    <i class="icon-car"></i>
                                </a>
                            </div>
                            <div><a href="#" class="text-default font-weight-semibold letter-icon-title">Auto & Transport</a></div>
                        </div>
                    </td>
                    <td class="text-right"><h6 class="text-muted mb-0">250.00</h6></td>
                    <td class="text-right"><h6 class="font-weight-semibold mb-0">0.00</h6></td>
                </tr>

                <tr>
                    <td>
                        <div class="d-flex align-items-center">
                            <div class="mr-3">
                                <a href="#" class="btn bg-indigo-400 rounded-round btn-icon btn-sm legitRipple">
                                    <i class="icon-store"></i>
                                </a>
                            </div>
                            <div><a href="#" class="text-default font-weight-semibold letter-icon-title">Food & Dining</a></div>
                        </div>
                    </td>
                    <td class="text-right"><h6 class="text-muted mb-0">2 000.00</h6></td>
                    <td class="text-right"><h6 class="font-weight-semibold mb-0">933.05</h6></td>
                </tr>

                <tr>
                    <td>
                        <div class="d-flex align-items-center">
                            <div class="mr-3">
                                <a href="#" class="btn bg-success-400 rounded-round btn-icon btn-sm legitRipple">
                                    <i class="icon-gift"></i>
                                </a>
                            </div>
                            <div><a href="#" class="text-default font-weight-semibold letter-icon-title">Gifts & Donations</a></div>
                        </div>
                    </td>
                    <td class="text-right"><h6 class="text-muted mb-0">2 000.00</h6></td>
                    <td class="text-right"><h6 class="font-weight-semibold mb-0">3 583.00</h6></td>
                </tr>

                <tr>
                    <td>
                        <div class="d-flex align-items-center">
                            <div class="mr-3">
                                <a href="#" class="btn bg-danger-400 rounded-round btn-icon btn-sm legitRipple">
                                    <i class="icon-bag"></i>
                                </a>
                            </div>
                            <div><a href="#" class="text-default font-weight-semibold letter-icon-title">Shopping</a></div>
                        </div>
                    </td>
                    <td class="text-right"><h6 class="text-muted mb-0">0.00</h6></td>
                    <td class="text-right"><h6 class="font-weight-semibold mb-0">0.00</h6></td>
                </tr>

                <!-- -->

                <tr>
                    <td>
                        <div class="d-flex align-items-center">
                            <div class="mr-3">
                                <a href="#" class="btn bg-primary-400 rounded-round btn-icon btn-sm legitRipple">
                                    <i class="icon-person"></i>
                                </a>
                            </div>
                            <div><a href="#" class="text-default font-weight-semibold letter-icon-title">Health & Medical</a></div>
                        </div>
                    </td>
                    <td class="text-right"><h6 class="text-muted mb-0">1 000.00</h6></td>
                    <td class="text-right"><h6 class="font-weight-semibold mb-0">377.64</h6></td>
                </tr>

                <tr>
                    <td>
                        <div class="d-flex align-items-center">
                            <div class="mr-3">
                                <a href="#" class="btn bg-danger-400 rounded-round btn-icon btn-sm legitRipple">
                                    <i class="icon-piggy-bank"></i>
                                </a>
                            </div>
                            <div><a href="#" class="text-default font-weight-semibold letter-icon-title">Investment & Vacation</a></div>
                        </div>
                    </td>
                    <td class="text-right"><h6 class="text-muted mb-0">12 000.00</h6></td>
                    <td class="text-right"><h6 class="font-weight-semibold mb-0">0.00</h6></td>
                </tr>

                <tr>
                    <td>
                        <div class="d-flex align-items-center">
                            <div class="mr-3">
                                <a href="#" class="btn bg-indigo-400 rounded-round btn-icon btn-sm legitRipple">
                                    <i class="icon-movie"></i>
                                </a>
                            </div>
                            <div><a href="#" class="text-default font-weight-semibold letter-icon-title">Entertainment</a></div>
                        </div>
                    </td>
                    <td class="text-right"><h6 class="text-muted mb-0">0.00</h6></td>
                    <td class="text-right"><h6 class="font-weight-semibold mb-0">0.00</h6></td>
                </tr>

                <tr>
                    <td>
                        <div class="d-flex align-items-center">
                            <div class="mr-3">
                                <a href="#" class="btn bg-success-400 rounded-round btn-icon btn-sm legitRipple">
                                    <i class="icon-graduation"></i>
                                </a>
                            </div>
                            <div><a href="#" class="text-default font-weight-semibold letter-icon-title">School</a></div>
                        </div>
                    </td>
                    <td class="text-right"><h6 class="text-muted mb-0">900.00</h6></td>
                    <td class="text-right"><h6 class="font-weight-semibold mb-0">0.00</h6></td>
                </tr>

                <tr>
                    <td>
                        <div class="d-flex align-items-center">
                            <div class="mr-3">
                                <a href="#" class="btn bg-danger-400 rounded-round btn-icon btn-sm legitRipple">
                                    <i class="icon-question7"></i>
                                </a>
                            </div>
                            <div><a href="#" class="text-default font-weight-semibold letter-icon-title">Other</a></div>
                        </div>
                    </td>
                    <td class="text-right"><h6 class="text-muted mb-0">1 000.00</h6></td>
                    <td class="text-right"><h6 class="font-weight-semibold mb-0">0.00</h6></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

resources/views/menu/element-activity.blade.php
                <li class="nav-item dropdown">
                    <a href="#" class="navbar-nav-link dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-pulse2 mr-2"></i>
                        Activity
                    </a>
                    
                    <div class="dropdown-menu dropdown-menu-right dropdown-content wmin-md-350">
                        <div class="dropdown-content-header">
                            <span class="font-size-sm line-height-sm text-uppercase font-weight-semibold">Latest activity</span>
                            <a href="#" class="text-default"><i class="icon-search4 font-size-base"></i></a>
                        </div>

                        <div class="dropdown-content-body dropdown-scrollable">
                            <ul class="media-list">
                                <li class="media">
                                    <div class="mr-3">
                                        <a href="#" class="btn bg-success-400 rounded-round btn-icon"><i class="icon-mention"></i></a>
                                    </div>

                                    <div class="media-body">
                                        <a href="#">Taylor Swift</a> mentioned you in a post "Angular JS. Tips and tricks"
                                        <div class="font-size-sm text-muted mt-1">4 minutes ago</div>
                                    </div>
                                </li>

                                <li class="media">
                                    <div class="mr-3">
                                        <a href="#" class="btn bg-pink-400 rounded-round btn-icon"><i class="icon-paperplane"></i></a>
                                    </div>
                                    
                                    <div class="media-body">
                                        Special offers have been sent to subscribed users by <a href="#">Donna Gordon</a>
                                        <div class="font-size-sm text-muted mt-1">36 minutes ago</div>
                                    </div>
                                </li>

                                <li class="media">
                                    <div class="mr-3">
                                        <a href="#" class="btn bg-blue rounded-round btn-icon"><i class="icon-plus3"></i></a>
                                    </div>
                                    
                                    <div class="media-body">
                                        <a href="#">Chris Arney</a> created a new <span class="font-weight-semibold">Design</span> branch in <span class="font-weight-semibold">Limitless</span> repository
                                        <div class="font-size-sm text-muted mt-1">2 hours ago</div>
                                    </div>
                                </li>

                                <li class="media">
                                    <div class="mr-3">
                                        <a href="#" class="btn bg-purple-300 rounded-round btn-icon"><i class="icon-truck"></i></a>
                                    </div>
                                    
                                    <div class="media-body">
                                        Shipping cost to the Netherlands has been reduced, database updated
                                        <div class="font-size-sm text-muted mt-1">Feb 8, 11:30</div>
                                    </div>
                                </li>

                                <li class="media">
                                    <div class="mr-3">
                                        <a href="#" class="btn bg-warning-400 rounded-round btn-icon"><i class="icon-comment"></i></a>
                                    </div>
                                    
                                    <div class="media-body">
                                        New review received on <a href="#">Server side integration</a> services
                                        <div class="font-size-sm text-muted mt-1">Feb 2, 10:20</div>
                                    </div>
                                </li>

                                <li class="media">
                                    <div class="mr-3">
                                        <a href="#" class="btn bg-teal-400 rounded-round btn-icon"><i class="icon-spinner11"></i></a>
                                    </div>
                                    
                                    <div class="media-body">
                                        <strong>January, 2018</strong> - 1320 new users, 3284 orders, $49,390 revenue
                                        <div class="font-size-sm text-muted mt-1">Feb 1, 05:46</div>
                                    </div>
                                </li>
                            </ul>
                        </div>

                        <div class="dropdown-content-footer bg-light">
                            <a href="#" class="font-size-sm line-height-sm text-uppercase font-weight-semibold text-grey mr-auto">All activity</a>
                            <div>
                                <a href="#" class="text-grey" data-popup="tooltip" title="Clear list"><i class="icon-checkmark3"></i></a>
                                <a href="#" class="text-grey ml-2" data-popup="tooltip" title="Settings"><i class="icon-gear"></i></a>
                            </div>
                        </div>
                    </div>
                </li>

resources/views/menu/element-connect.blade.php
                <li class="nav-item dropdown">
                    <a href="#" class="navbar-nav-link dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-make-group mr-2"></i>
                        Connect
                    </a>

                    <div class="dropdown-menu dropdown-menu-right dropdown-content wmin-md-350">
                        <div class="dropdown-content-body p-2">
                            <div class="row no-gutters">
                                <div class="col-12 col-sm-4">
                                    <a href="#" class="d-block text-default text-center ripple-dark rounded p-3">
                                        <i class="icon-github4 icon-2x"></i>
                                        <div class="font-size-sm font-weight-semibold text-uppercase mt-2">Github</div>
                                    </a>

                                    <a href="#" class="d-block text-default text-center ripple-dark rounded p-3">
                                        <i class="icon-dropbox text-blue-400 icon-2x"></i>
                                        <div class="font-size-sm font-weight-semibold text-uppercase mt-2">Dropbox</div>
                                    </a>
                                </div>
                                
                                <div class="col-12 col-sm-4">
                                    <a href="#" class="d-block text-default text-center ripple-dark rounded p-3">
                                        <i class="icon-dribbble3 text-pink-400 icon-2x"></i>
                                        <div class="font-size-sm font-weight-semibold text-uppercase mt-2">Dribbble</div>
                                    </a>

                                    <a href="#" class="d-block text-default text-center ripple-dark rounded p-3">
                                        <i class="icon-google-drive text-success-400 icon-2x"></i>
                                        <div class="font-size-sm font-weight-semibold text-uppercase mt-2">Drive</div>
                                    </a>
                                </div>

                                <div class="col-12 col-sm-4">
                                    <a href="#" class="d-block text-default text-center ripple-dark rounded p-3">
                                        <i class="icon-twitter text-info-400 icon-2x"></i>
                                        <div class="font-size-sm font-weight-semibold text-uppercase mt-2">Twitter</div>
                                    </a>

                                    <a href="#" class="d-block text-default text-center ripple-dark rounded p-3">
                                        <i class="icon-youtube text-danger icon-2x"></i>
                                        <div class="font-size-sm font-weight-semibold text-uppercase mt-2">Youtube</div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>

resources/views/menu/element-greet.blade.php
            <span class="navbar-text ml-md-3">
                <span class="badge badge-mark border-orange-300 mr-2"></span>
                Morning, Victoria!
            </span>

resources/views/menu/header-elements.blade.php
                        <div class="d-flex justify-content-center">
                            <a href="#" class="btn btn-link btn-float font-size-sm font-weight-semibold text-default">
                                <i class="icon-bars-alt text-pink-300"></i>
                                <span>Statistics</span>
                            </a>
                            <a href="#" class="btn btn-link btn-float font-size-sm font-weight-semibold text-default">
                                <i class="icon-calculator text-pink-300"></i>
                                <span>Invoices</span>
                            </a>
                            <a href="#" class="btn btn-link btn-float font-size-sm font-weight-semibold text-default">
                                <i class="icon-calendar5 text-pink-300"></i>
                                <span>Schedule</span>
                            </a>
                        </div>

resources/views/menu/profile-menu.blade.php
<ul class="nav nav-sidebar">
    <li class="nav-item">
        <a href="#" class="nav-link">
            <i class="icon-user-plus"></i>
            <span>My profile</span>
        </a>
    </li>
    <li class="nav-item">
        <a href="#" class="nav-link" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
            <i class="icon-switch2"></i>
            <span>Logout</span>
        </a>
    </li>
</ul>

resources/views/menu/sidebar-menu.blade.php
<ul class="nav nav-sidebar" data-nav-type="accordion">
    <li class="nav-item-header"><div class="text-uppercase font-size-xs line-height-xs">Main</div> <i class="icon-menu" title="Main"></i></li>
    <li class="nav-item">
        <a href="{{route('dashboard')}}" class="nav-link {!! Auth::user()->uriSegment(2) === '' ? 'active' : '' !!}">
            <i class="icon-home4"></i><span>Dashboard</span>
        </a>
    </li>
    <li class="nav-item">
        <a href="{{route('applications-admin.index')}}" class="nav-link {!! Auth::user()->uriSegment(2) === 'applications-admin' ? 'active' : '' !!}">
            <i class="icon-drawer3"></i><span>Applications</span>
        </a>
    </li>
    <li class="nav-item nav-item-submenu">
        <a href="#" class="nav-link"><i class="icon-users"></i> <span>Users</span></a>
        <ul class="nav nav-group-sub" data-submenu-title="Users">
            <li class="nav-item"><a href="{{ route('users.index') }}" class="nav-link {!! Auth::user()->uriSegment(2) === 'users' ? 'active' : '' !!}">User list</a></li>
            <li class="nav-item"><a href="{{ route('roles.index') }}" class="nav-link {!! Auth::user()->uriSegment(2) === 'roles' ? 'active' : '' !!}">Roles</a></li>
            <li class="nav-item"><a href="{{ route('permissions.index') }}" class="nav-link {!! Auth::user()->uriSegment(2) === 'permissions' ? 'active' : '' !!}">Permissions</a></li>
        </ul>
    </li>
    <li class="nav-item">
        <a href="{{route('pages.index')}}" class="nav-link {!! Auth::user()->uriSegment(2) === 'pages' ? 'active' : '' !!}">
            <i class="icon-stack-text"></i><span>Pages</span>
        </a>
    </li>
    <li class="nav-item">
        <a href="{{route('options')}}" class="nav-link {!! Auth::user()->uriSegment(2) === 'options' ? 'active' : '' !!}">
            <i class="icon-cog"></i><span>Options</span>
        </a>
    </li>

</ul>